## Revision- Python Basics

In [1]:
from IPython.display import Image

import numpy as np
import pandas as pd

### 1. Write 2 `mutable` data-types of python:

### 2. Write 2 `immutable` data-types of python:

### Bullet Points 
 - every variable is Python is an **object instance**. 
 - When an object is created, it is assigned a unique **object id**. 
 - The type of that **object** is defined at **runtime** 
 - For an object, **object id can never change**
 - The **state** of that object **can be changed** if it is mutable. 
 - A **mutable** object can be changed after it is created, and an **immutable** object can’t be.    

In [ ]:
#case 1:
x = [1,2,3]
y = x
x.pop()

### 3. is id(x) == id(y) ?

In [ ]:
id(x) == id(y)

In [ ]:
#case 2:
x = 3; y = x; x = x +1

### 4. is id(x) == id(y) ?

In [ ]:
id(x), id(y)

In [ ]:
id(x) == id(y)

### 5. Find all errors in the function definition below <br>

In [ ]:
func add elems:(k=3,r)
x = r + k
return X

add elems(2,3)

### 6. Define a class:

Upon initialisation (`__init__`), the class should take a string from console input 

The class should have 2 methods: <br>
`get_upper`: to return the string in upper case. <br>
`get_lower`: to return the string in lower case.

In [ ]:
s = InputOutString()

In [ ]:
s.get_upper()

In [ ]:
s.get_lower()

# Numpy Quick Recap

In [ ]:
Image(filename='../images/np_arrays.png')

### Bullent Points: NumPy Array
 1. _**Attributes of arrays**_: Determining the size, shape, memory consumption, and data types of arrays <br>
 `ndarray.size`   `ndarray.shape`   `ndarray.dtype`
 2. _**Indexing of arrays**_: Getting and setting the value of individual array elements <br>
 `array[r,c]`
 3. _**Slicing of arrays**_: Getting and setting smaller subarrays within a larger array <br>
 `array[start_row:end_row, start_col:end_col]` <br>
 `row_indices=[r1,r2,..]; col_indices=[c1,c2..]; array[row_indices, col_indices]`
 4. _**Reshaping of arrays**_: Changing the shape of a given array <br>
 `array.reshape(r,c)`
 5. _**Joining and splitting of arrays**_: Combining multiple arrays into one, and splitting one array into many <br>
 `np.vstack` `np.hstack` `np.tile`

In [ ]:
Image(filename='images/np_broadcasting.png', width=800)

### 7. Using `lst` generate `arrint` as shown:

In [ ]:
lst = [1,2,3,4.0]

In [ ]:
array

### 8. Write a function to generate a list of all even numbers between 0 to 100

### 9. Write the same function as a list comprehension

### 10. For the above function, return the output as a 2D array with 2 rows

### 11. What are the different attributes of an array?

### 12. Write 5 array generating functions: (like numpy.arange())

### 13. From array `a`, create array `b` as a deep copy:

In [20]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b

array([[ 6,  7],
       [10, 11]])

### 14. Reshape arr into 2D array with 3 rows:

In [31]:
twoD_arr = np.arange(1, 46)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]])

- The criterion to satisfy for providing the new shape is that _'The new shape should be compatible with the original shape'_
- numpy allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). 
- It simply means that it is an unknown dimension and we want numpy to figure it out. And numpy will figure this by looking at the 'length of the array and remaining dimensions' and making sure it satisfies the above mentioned criteria

### 15. From the array `twenty` below, generate the `result` as shown

In [ ]:
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty

In [ ]:
result

### 16. Using conditional statements, generate `result` from `range_arr` as shown:

In [33]:
range_arr = np.arange(0, 10, 0.5)
range_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

``
result = array([5.5, 6. , 6.5, 7. ])
``

array([5.5, 6. , 6.5, 7. ])

### 17. Using array `a` and `b`, create `vs` and `hs` as shown:

In [45]:
a = np.array([[1, 2], [3, 4]])
print(a.shape);a

(2, 2)


array([[1, 2],
       [3, 4]])

In [46]:
b = np.array([[5, 6]])
print(b.shape);b

(1, 2)


array([[5, 6]])

```python

vs = 
array([[1, 2],
       [3, 4],
       [5, 6]])
```

```python
hs = array([[1, 2, 5],
            [3, 4, 6]])
```

### 18. From the given array, generate row wise and column wise average as shown:

In [52]:
arr = np.arange(5 * 6).reshape(5, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
col_avg 

array([12., 13., 14., 15., 16., 17.])

In [54]:
row_avg 

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

### 19. Show how to do this?

Suppose that X is a data matrix of shape `(n,p)`. That is, there are `n` data points and `p` features per point. Often, we have to remove the mean from each feature. That is, we want to compute the mean for each feature and then remove the mean from each column. 

In [61]:
# say n =10, and p =30
n = 10
p = 30
X = np.random.rand(n,p)
X.shape

(10, 30)

In [62]:
mean = X.mean(axis=0)

In [63]:
mean.shape

(30,)

In [69]:
right1 = X - mean

In [70]:
right = X - mean.reshape(1,30)

In [72]:
np.all(right1 == right)

True

### 20. Load the cars.csv as a dataframe.

In [73]:
file='data/cars.csv'

In [81]:
cars = 

Retail  Dealer  Engine  Cylinders  Horsepower  \
Name                                                                      
Acura 3.5 RL               43755   39014     3.5          6         225   
Acura 3.5 RL Navigation    46100   41100     3.5          6         225   
Acura MDX                  36945   33337     3.5          6         265   
Acura NSX S                89765   79978     3.2          6         290   
Acura RSX                  23820   21761     2.0          4         200   
Acura TL                   33195   30299     3.2          6         270   
Acura TSX                  26990   24647     2.4          4         200   
Audi A4 1.8T               25940   23508     1.8          4         170   
Audi A4 1.8T convertible   35940   32506     1.8          4         170   
Audi A4 3.0 convertible    42490   38325     3.0          6         220   

                          CityMPG  HighwayMPG  Weight  Wheelbase  Length  \
Name                                                                       
Acura 3.5 RL                   18          24    3880        115     197   
Acura 3.5 RL Navigation        18          24    3893        115     197   
Acura MDX                      17          23    4451        106     189   
Acura NSX S                    17          24    3153        100     174   
Acura RSX                      24          31    2778        101     172   
Acura TL                       20          28    3575        108     186   
Acura TSX                      22          29    3230        105     183   
Audi A4 1.8T                   22          31    3252        104     179   
Audi A4 1.8T convertible       23          30    3638        105     180   
Audi A4 3.0 convertible        20          27    3814        105     180   

                          Width  
Name                             
Acura 3.5 RL                 72  
Acura 3.5 RL Navigation      72  
Acura MDX                    77  
Acura NSX S                  71  
Acura RSX                    68  
Acura TL                     72  
Acura TSX                    69  
Audi A4 1.8T                 70  
Audi A4 1.8T convertible     70  
Audi A4 3.0 convertible      70

### 21. Using `loc` or `iloc` select the observation corresponding to `Audi A6 3.0` as a Series. The label of this row is `Audi A6 3.0` , the index is 15.

Indexing in Pandas can be done in 4 ways:
1.`[ ]` 2. ` . ` 3. `loc`  4. `iloc`

- With `loc` and `iloc` you can do practically any data selection operation on DataFrames. 
- `loc` is `label-based`, which means that you have to specify rows and columns based on their row and column labels. 
- `iloc` is `integer index based`, so you have to specify rows and columns by their integer index like you did in the previous exercise.

### 22. Load the `loans data.csv` into a dataframe. 
- Display the first 3 and last 3 rows. 
- Check no of data points,
- no of feature points corresponding to a given data point, 
- column labels, 
- columns dtypes, 

In [88]:
file='data/loans data.csv'

In [90]:
ld 

### 23. In the `loans data` display all the unique types of Home.Ownership along with their total couts/frequency

### 24. From the loans data, create a new csv with only `Home.Ownership` and  `Monthly.Income` as the cols. Also, select only the data points which have `Home.Ownership == MORTGAGE` and `Monthly.Income > 5000`

### 25. In the previous data, for each Home Ownership type calculate the mean monthly income

### 26. In the loans data, identify column that has highest no of missing values

### 27. From the previous question, remove all data points that have missing values corresponding to the column you have identified.

## Bonus Questions

## 1. Compute Eigen Value and Eigen Vectors

 - Every vector (list of numbers) has a direction when it is plotted on a XY chart.
 
 - Consider A to be any square matrix. Now, almost all vectors will change direction, when they are multiplied by A. Certain exceptional vectors x are in the same direction as Ax, i.e. the direction of x and Ax will be the same. Those are the “eigenvectors”. Multiply an eigenvector by A, and the vector Ax is a number () times the original x. The number () is called the "eigenvalue".
 
 - An eigenvector is a vector whose direction remains unchanged when a linear transformation is applied to it.
 
 - Eigen value— The scalar that is used to transform an Eigenvector.
 
 - The eigenvalue tells whether the special vector x is stretched or shrunk or reversed or left unchanged—when it is multiplied by A. 

`A * eigen_vector — eigen_value * eigen_vector = 0`

In [ ]:
arr = np.arange(0,9).reshape(3,3)
arr

### 2. Write a Python class named Circle constructed by a radius and two methods which will compute the area and the perimeter of a circle.

### 3. Write a function to convert a list to dictionary as shown: 

`mylist = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine']`

`mydict = 
{
    0 : 'Zero',
    1 : 'One',
    2 : 'Two',
    3 : 'Three',
    4 : 'Four',
    5 : 'Five',
    6 : 'Six',
    7 : 'Seven',
    8 : 'Eight',
    9 : 'Nine',
}`

In [ ]:
x = ['Zero', 'One', 'Two', 'Three', 'Four']

In [ ]:
d = list_to_dict(x)
d

### 3. Binary Search

Given a sorted array arr[] of n elements, write a function to search a given element x in arr[].

A simple approach is to do linear search.The time complexity of above algorithm is O(n). Another approach to perform the same task is using Binary Search. 

In Binary search, we search a sorted array by repeatedly dividing the search interval in half. Begin with an interval covering the whole array. If the value of the search key is less than the item in the middle of the interval, narrow the interval to the lower half. Otherwise narrow it to the upper half. Repeatedly check until the value is found or the interval is empty.

In [ ]:
# Test array 
arr = [ 2, 3, 4, 10, 40 ] 
x = 10
  
# Function call 
result = binarySearch(arr, 0, len(arr)-1, x) 
  
if result != -1: 
    print("Element is present at index %d" % result)
else: 
    print("Element is not present in array")

### 4. Given a list of numbers, write a function to return outliers?

#### How are outliers defined?

Here we can assume that outliers are defined as numbers outside of `[Q1 - 1.5 * IQR, Q3 + 1.5 * IQR]`
where `Q1` is the first quartile, `Q3` is the third quartile, and `IQR` is the inner quartile range `(Q3 - Q1)`

The runtime of this algorithm is at least O(n), but potentially larger depending on how numpy computes quartiles.

In [ ]:
L = [1,2,3,4,6,1,2,3,4,6,1,99,-100,1,2,3,4,5,2,2,22,34,1,2,3,4,-10]
findOutliers(L)