# Intro-to-Numerical-Python (NumPy)

## Getting Started

- NumPy's main object is the **homogeneous** ***multidimensional array***. It is a table of elements (usually numbers), all of the same type. 

- In Numpy dimensions are called **axes**. 

- The number of axes is called **rank**. 

### Multidimensional Array

 - The data structure is actually called `ndarray`, representing any number of dimensions
 - Arrays can have _multiple dimensions_, you declare them on creation
 - Dimensions help define what each element in the array represents. A two dimensional array is just an array of arrays
 - _Rank_ defines how many dimensions an array contains
 - Shape defines the length of each of the array's dimensions
 - Each dimension is also referred to as an axis, and they are _zero-indexed_. Multiples are called axes.
 - A 2d array is AKA matrix.

<center><img src="images/np_arrays.png" width="80%"/></center>

To use `numpy`, import the module using the example below:

In [1]:
import numpy as np  # naming import convention

Let's start by creating some `numpy.array` objects in order to get our hands into the very details of **numpy basic data structure**.

NumPy is a very flexible library, and provides many ways to create (and initialize) new numpy arrays. 

#### Create a 2D array

Define the below array in numpy

```python
myarray = array([
                 [1, 2, 3, 4],
                 [4, 5, 6, 7]
                ])
```

In [ ]:
# TO DO: Define the array

myarray = np.array([
                    [1, 2, 3, 4],
                    [4, 5, 6, 7]
                   ])


In [ ]:
myarray.shape

In [ ]:
mylist = [1, 2, 3, 4, 5, 6]
mylist

In [ ]:
# 
myarray = np.array(mylist)
myarray

In [ ]:
type(myarray)

### So, why is it useful then?

So far the `numpy.ndarray` looks awefully much like a Python **list** (or **nested list**). 

*Why not simply use Python lists for computations instead of creating a new array type?*

There are several reasons:

* Python lists are very general. 
    - They can contain any kind of object. 
    - They are dynamically typed. 
    - They do not support mathematical functions such as matrix and dot multiplications, etc. 
    - Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
    
    
* Numpy arrays are **statically typed** and **homogeneous**. 
    - The type of the elements is determined when array is created.
    
    
* Numpy arrays are memory efficient.
    - Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

### Differences between lists and NumPy Arrays

 - An array's size is immutable. You cannot append, insert or remove elements, like you can with a list.
 - All of an array's elements must be of the same data type.
 - A NumPy array behaves in a Pythonic fashion. You can `len(my_array)` just like you would assume.

In [ ]:
# Can have elements appended to it
mylist.append(4.0)

# Can have multiple datatypes in it.
mylist.insert(1, "notnum")

# Can have items removed
mylist.pop(1)

## Attributes of arrays

The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

In [ ]:
myarray1 = np.array([
                    [1, 2, 3, 4],
                    [4, 5, 6, 7]
                   ])

myarray2 = np.array([
                    [1.0, 2, 3, 4],
                    [4, 5.5, 6, 7]
                   ])

myarray3 = np.array([
                    [1.0, 2, 3, 4],
                    [4, 5.5, 6, 7],
                    [2.0, 2.6, 3, 4],
                   ])

In [ ]:
myarray1.dtype

In [ ]:
myarray2.dtype

In [ ]:
myarray3.dtype

In [ ]:
myarray1.size, myarray2.size, myarray3.size,

In [ ]:
myarray1.itemsize # bytes per element

In [ ]:
myarray2.itemsize

In [ ]:
myarray3.itemsize

In [ ]:
myarray.nbytes # number of bytes

`ndarray.shape`: gives the dimensions of the array. 
- This is a tuple of integers indicating the size of the array in each dimension. 
- For a matrix with `n rows` and `m columns`, shape will be `(n,m)`. 
- The length of the shape tuple is therefore the number of axes, ndim.

You can determine dimension of array with attribute shape

In [ ]:
myarray.shape # (rows, colums)      

## Reshaping of arrays
Changing the shape of a given array <br>
- `array.reshape(r,c)`

In [ ]:
myarray

In [ ]:
myarray.shape

In [ ]:
myarray.reshape(4, 2)

In [ ]:
myarray.reshape(4, -1)

In [ ]:
myarray.reshape(4, 3)

In [ ]:
myarray.reshape(-1,2)

## Array Generating functions 
 - np.arange
 - numpy.zeros
 - numpy.ones
 - numpy.empty
 - numpy.linspace
 - numpy.random
 - numpy.eye


1. To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [ ]:
temp = np.arange(10, 50, 5).reshape(2, -1)
temp

In [ ]:
temp = np.arange(10, 30, 5).reshape(2,2)
temp

In [ ]:
temp.shape, temp.ndim

In [ ]:
np.arange(10).reshape(1,-1)

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. 

The function: <br>
2. **zeros** creates an array full of zeros, the function <br>
3. **ones** creates an array full of ones, and the function <br>
4. **empty** creates an array whose initial content is random and depends on the state of the memory. 

In [ ]:
# numpy.zeros(shape, dtype=float)
# shape : int or tuple of ints
Z = np.zeros((2,2), dtype="int")
Z

In [ ]:
type(Z), Z.dtype

In [ ]:
# numpy.ones(shape, dtype=float)
O = np.ones((3,2,3))
O

In [ ]:
O.dtype

In [ ]:
np.ones((2,3,4), dtype=np.int16)

In [ ]:
np.empty((2,3)) 

### `np.linspace` and `np.logspace`

Like `np.arange`, in numpy there are other two "similar" functions: 

- np.linspace
- np.logspace

Looking at the examples below, can you spot the difference?

In [ ]:
np.linspace(0, 10, 20).reshape(4,5)

In [ ]:
np.logspace(0, np.e**2, 10, base=np.e).reshape(5,2)

In [ ]:
import math

In [ ]:
# All constants
np.full((2,2), math.pi)

In [ ]:
# One more example with all constants
np.full((3,2),4,dtype=int)

In [ ]:
# Identity Matrix
np.eye(5)

In [ ]:
# Random numbers from [0,1]
np.random.random((4,3))

As a side note ,  single random number from [0,1) can be obtained like this 

In [ ]:
np.random.random()

To obtain a number in the interval [a,b), you can simply multiply above with (b-a) and then add a.

In [ ]:
# random number from [5,95]
90*np.random.random()+5

## Numerical Types and Precision

In NumPy, talking about `int` or `float` does not make "real sense". This is mainly for two reasons:

(a) `int` or `float` are assumed at the maximum precision available on your machine (presumably `int64` and 
`float64`, respectively.

(b) Different precision imply different numerical ranges, and so different memory size (i.e. _number of bytes_ required to represent all the numbers in the corresponding numerical range).

Numpy support the following numerical types:

    bool             | This stores boolean (True or False) as a bit

    int0             | This is a platform integer (normally either int32 or int64)
    int8             | This is an integer ranging from -128 to 127
    int16            | This is an integer ranging from -32768 to 32767
    int32            | This is an integer ranging from -2 ** 31 to 2 ** 31 -1
    int64            | This is an integer ranging from -2 ** 63 to 2 ** 63 -1
    
    uint8            | This is an unsigned integer ranging from 0 to 255
    uint16           | This is an unsigned integer ranging from 0 to 65535
    uint32           | This is an unsigned integer ranging from 0 to 2 ** 32 - 1
    uint64           | This is an unsigned integer ranging from 0 to 2 ** 64 - 1

    float16          | This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa
    float32          | This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa
    float64 or float | This is a double precision float with sign bit, 11 bits exponent, and 52 bits mantissa
    complex64        | This is a complex number represented by two 32-bit floats (real and imaginary components)
    complex128       | This is a complex number represented by two 64-bit floats (real and imaginary components)
    (or complex)


### Numerical Types and Representation

The **numerical dtype** of an array should be selected very carefully, as it directly affects the numerical representation of elements, that is: 

   * the number of **bytes** used; 
   * the *numerical range*

We can **always specify** the `dtype` of an array when we create one. If we do not, the `dtype` of the array will be inferred, namely `np.int_` or `np.float_` depending on the case.

In [ ]:
a = np.arange(-1,10)
print(a)
print(a.dtype)
print(a.itemsize)

In [ ]:
au = np.arange(-1,10, dtype=np.int16)
print(au)
print(au.dtype)
print(au.itemsize)

## Indexing of arrays
Getting and setting the value of individual array elements <br>
- `array[r,c]`

Individual elements of these arrays can be accessed by passing indices in square brackets. The format is `array[r, c]` or `array[r][c]`. Lets see few examples 

In [ ]:
# Create a 2D array
arr = np.array([[1,2.,3,4],[4,5.2,6,7]])   
arr

In [ ]:
arr.dtype

In [ ]:
arr[0, 0], arr[0, 1], arr[1, 1], arr[1, 2] 

In [ ]:
arr[0][0], arr[0][1], arr[1][1], arr[1][2]

arr[0,1] = arr[0][1] though the second case is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.

## Slicing of arrays
Getting and setting smaller subarrays within a larger array <br>
- `array[start_row:end_row, start_col:end_col]` <br>
- `row_indices=[r1,r2,..]; col_indices=[c1,c2..]; array[row_indices, col_indices]`

In [ ]:
arr = np.linspace(0,10,15).reshape(5,3)
arr

In [ ]:
id(arr)

In [ ]:
arr1 = arr.reshape(3,5)

In [ ]:
id(arr1)

In [ ]:
slic = arr[1:3,:].copy()
slic

In [ ]:
slic.shape

In [ ]:
slic[0,0] = 1
slic

In [ ]:
arr

### Dependence of subset of an array

One important thing that you need to keep in mind is that a subset of a numpy array doesnt become an independent array . If you make any changes in that , they reflect in the parent array. you need to use function copy to make an independent array. Lets understand that with an example

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
b = a[:2, 1:3]   
print("this is b",":\n",b)
# b is still part of a , not an independent array

In [ ]:
a.dtype, b.dtype

In [ ]:
b[0,0]= 4
# b=b*3

In [ ]:
b

In [ ]:
a

In [ ]:
c = a[:2, 1:3].copy()
print("this is c",":\n",c)
# c is independent of a, its a fresh array

Lets look at element a[0,1] , this is same as b[0,0]

In [ ]:
print(a)
print(a[0, 1])
print(b[0, 0])

In [ ]:
b[0, 0] = 77
# notice that we are not changing "a" here
print(a)

You can see that although we changed value for b[0,0] but that ended up changing value for a[0,1] too. now lets look at a[0,2] which is same as c[0,1] . lets see if chaning c[0,1] has any effect on a[0,2].


In [ ]:
a

In [ ]:
c

In [ ]:
print(a[0,2])
print(c[0,1])

In [ ]:
a

In [ ]:
c[0, 1] = 99
print(a)
print(c)

### More on accessing arrays with indices
Its not necessary that when you are accessing elements of array; index values have to be continuous . They can be any number as long as they do not go out of range of exsiting element positions.

- `row_indices=[r1,r2,..]; col_indices=[c1,c2..]; array[row_indices, col_indices]`

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

In [ ]:
# slicing at particular (r,c) positions
a[[0, 1, 2], [0, 1, 0]] # a[[r1, r2, r3], [c1, c2, c1]]

In [ ]:
# slicing for certain rows
a[[0, 2],] # a[[r1, r2, r3], [c1, c2, c3]]

In [ ]:
# another example
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
a

In [ ]:
b = np.array([0, 2, 0, 1])
b

In [ ]:
c=np.arange(4)
c

In [ ]:
a[c, b]

Using index you can access elements as well as modify them

In [ ]:
a

In [ ]:
a[c, b] += 10
a

### Conditional Access of arrays
if "a" here was a single element , wirintg a>2 wil generate True or False depeneding on whetrher that particular condition was true.

Now when "a" is a numpy array, that comparison will be done for each element and result will be an array of shape same as "a"->containing True/False for each element.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

In [ ]:
c = a > 2
print(c)

In [ ]:
c.dtype

We can use , these comparison expressions directly for access. Result is only those elements for which the expression evaluates to True

In [ ]:
print(a[c])
print(a[c].shape)

In [ ]:
a

In [ ]:
b = a[a>2].copy()
b

In [ ]:
a = np.linspace(0,10,10).reshape((2,5))
a

In [ ]:
b = np.linspace(0,5,10).reshape((2,5))
b

In [ ]:
#b[a>5] = a[a>5]
b[a>5] = 10

In [ ]:
b

notice that the result is also a 2D array.

Lets see if this works with writing mulitple conditions as well. 

In that process we'll also see that we dont have to store results in one variable and then pass for subsetting. We can instead, write the conditional expression directly for subsetting.

In [ ]:
a

In [ ]:
r = a[(a>2) | (a<5)] 
r

In [ ]:
z = a[(a>2) & (a<5)]
z

In [ ]:
q = a[~(a>2)]
q

## Array Operations

### Basic Mathematical Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

We'll see that you can use ; both normal symbols as well as numpy functions for array operations. Lets look at these operations with examples

In [2]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [3]:
x

array([[1, 2],
       [3, 4]])

In [4]:
y

array([[5, 6],
       [7, 8]])

In [5]:
x+y

array([[ 6,  8],
       [10, 12]])

In [6]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [7]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [8]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [9]:
# element wise multiplication
print(x)
print("~~~~~")

print(y)
print("~~~~~")
print(x * y)

[[1 2]
 [3 4]]
~~~~~
[[5 6]
 [7 8]]
~~~~~
[[ 5 12]
 [21 32]]


In [10]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [11]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In general you'll find that , mathematical functions from numpy [being referred as np here ] when applied on array, give back result as an array where that function has been applied on individual elements. 

In [13]:
x

array([[1, 2],
       [3, 4]])

In [14]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [15]:
# illegal operations
a = np.array([1,2,3,4])
b = np.array([1,2,3,4,5])

c = a + b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

### Flattening

Another (quite common) reshaping operation you will end up performing on n-dimensional arrays is **flattening**.

Flattening means _collapsing all the axis into a unique one_

#### `np.ravel`

`numpy.ndarray` objects have a `ravel` method that generates a new version of the array as a `1D` vector. 

Also this time, the original memory is unaffected, and a pointer with different metadata is returned.

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
A.ravel()

array([1, 2, 3, 4, 5, 6])

By default, the `np.ravel` performs the operation _row-wise_ . Numpy also support a Fortran-style order of indices (i.e. _column-major_ indexing)

In [18]:
A.ravel('F')  # order F (Fortran) is column-major, C (default) row-major

array([1, 4, 2, 5, 3, 6])

**Alternatively** We can also use the function `np.flatten` to make a higher-dimensional array into a vector. But this function create a copy of the data.

### Transpose

Similarly, we can transpose a matrix

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
A.T.ravel('F')

array([1, 2, 3, 4, 5, 6])

### np.dot
numpy.dot(a, b)
 - If both a and b are 1-D arrays, it is inner product of vectors
 - If both a and b are 2-D arrays, it is matrix multiplication
 
<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

<br> 
For Dot product between 2D matrix:

(nXm) . (mXc) = (nxc)

In [23]:
v = np.array([9,10])
v

array([ 9, 10])

In [24]:
w = np.array([11, 12])
w

array([11, 12])

In [25]:
v.shape, w.shape

((2,), (2,))

In [26]:
np.dot(v,w)

219

In [27]:
# Matrix multiplication
v.dot(w)

219

You can see that result is not what you'd expect from matrix multiplication. This happens because a single dimensional array is not a matrix.

We can make them to be 2X1 matrices by manually applying that shape to them

In [28]:
v=v.reshape((1,2))
w=w.reshape((1,2))

In [29]:
print(v.shape)
print(w.shape)

(1, 2)
(1, 2)


Now if you simply try to do v.dot(w) or np.dot(v,w) [both are same] , you will get and error because you cannot multiple a matrix of shape 2X1 with a matrix of 2X1.

In [30]:
np.dot(v,w.T)

array([[219]])

In [31]:
print(f'matrix v: {v} with shape: {v.shape}')
print(f'matrix v Transpose: {v.T} with shape {v.T.shape}')
print(f'matrix w: {w} with shape: {w.shape}')
print(f'matrix w Transpose: {w.T} with shape {w.T.shape}')
print('~~~~~~~~~')
print("np.dot(v,w.T): ", np.dot(v,w.T))
print('~~~~~~~~~')
print("np.dot(v.T,w): ", np.dot(v.T,w))

matrix v: [[ 9 10]] with shape: (1, 2)
matrix v Transpose: [[ 9]
 [10]] with shape (2, 1)
matrix w: [[11 12]] with shape: (1, 2)
matrix w Transpose: [[11]
 [12]] with shape (2, 1)
~~~~~~~~~
np.dot(v,w.T):  [[219]]
~~~~~~~~~
np.dot(v.T,w):  [[ 99 108]
 [110 120]]


If you leave v to be a single dimensional array . you will simply get an element wise multiplication. Here is an example

In [32]:
print(x)
v=np.array([9,10])
print("~~~~~")
print(v)
x.dot(v)

[[1 2]
 [3 4]]
~~~~~
[ 9 10]


array([29, 67])

In [33]:
print(x)
print("~~~")
print(y)
x.dot(y)

[[1 2]
 [3 4]]
~~~
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

## Math Functions

`sum`, `max`, `min`, `mean`, `std`, `argmax`, `argmin`

In [36]:
a = np.array([-4, -2, 1, 5, 3])

In [37]:
a.sum()

3

In [38]:
a.max()

5

In [39]:
a.min()

-4

In [42]:
a.mean()

0.6

In [43]:
a.std()

3.261901286060018

In [40]:
a.argmax()

3

In [ ]:
a[a.argmax()]

In [41]:
a.argmin()

0

## Saving data

`np.save(filename, ndarray)`

In [44]:
a

array([-4, -2,  1,  5,  3])

In [45]:
import os
os.getcwd()

'C:\\Users\\Pradip.Gupta\\Dropbox\\personal-projects\\intro-to-ml-with-python\\src\\week2'

In [48]:
path = os.path.join(os.getcwd(),"data")

In [49]:
np.save(path+"/temp.npy",a)

In [50]:
del a

In [52]:
a = np.load("./data/temp.npy")

In [53]:
a

array([-4, -2,  1,  5,  3])

## Stacking and repeating arrays

Using function `np.repeat`, `np.tile`, `np.vstack`, `np.hstack`, and `np.concatenate` we can create larger vectors and matrices from smaller ones:

### `np.tile` and `np.repeat`

In [54]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

#### `np.repeat`

In [55]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

#### `np.tile`

In [56]:
# tile the matrix 3 times 
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

### `np.concatenate`

In [57]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [58]:
a

array([[1, 2],
       [3, 4]])

In [59]:
np.concatenate((a, b), axis=0) #column-wise

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
np.concatenate((a, b.T), axis=1) #row-wise

array([[1, 2, 5],
       [3, 4, 6]])

### `np.hstack` and `np.vstack`

In [61]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.shape, b.T.shape

In [62]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## Vectorizing functions

- to get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. 
- The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [63]:
import numpy as np

def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [64]:
arg = np.linspace(-5,5,1000)

In [65]:
Theta(arg)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

OK, that didn't work because we didn't write the `Theta` function so that it can handle with vector input... 

In [68]:
np.array(list(map(Theta,arg)))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### `np.vectorize`

In [69]:
Theta_vec = np.vectorize(Theta)

In [70]:
Theta_vec(arg)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# Vectorisation and Broadcasting

**Vectorizing** code is the key to writing efficient numerical calculation with Python/Numpy. 

That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like **matrix-matrix multiplication**.

However, sometimes it may happen that we need to perform operations between `ndarray` objects of different size and shape so **we might be tempted of performing this operation** explicitly (i.e. _explicit for loop_).

Although we will get correct results (assumed we iterated arrays in the right way), this will produce **very inefficient** code.

For this reason, NumPy has a very important concept called **Broadcasting**.

_Broadcasting_ is Numpy's terminology for performing mathematical operations between arrays with different shapes (assuming _scalars_ being array with `0-dim`).

## Broadcasting

<center><img src="images/np_broadcasting.png" width="80%"/></center>

### Working example

Assume we have some data in a matrix `D`:

In [75]:
D = np.array([ [0.3, 2.5, 3.5],
               [2.9, 27.5, 0],
               [0.4, 1.3, 23.9],
               [14.4, 6, 2.3]])

And we also have another vector `adj` of values that contains some adjusting factors that we might want to apply to each sample (row) of data in `D`

In [77]:
adj = np.array([9, 4, 4])

### Naive Solution

In [78]:
%%timeit

# Create a new array filled with zeros, of the same shape as macros.
result = np.zeros_like(D)

# Now multiply each row of macros by cal_per_macro. In Numpy, `*` is
# element-wise multiplication between two arrays.
for i in range(D.shape[0]):
    result[i, :] = D[i, :] * adj
    
result

8.25 µs ± 45.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


This is a reasonable approach when coding in a low-level programming language: allocate the output, loop over input performing some operation, write result into output. 

In Numpy, however, this is fairly bad for performance because the looping is done in (slow) Python code instead of internally by Numpy in (fast) C code

(we've proven this already when we compared `ndarray` vs `list`)

### Using `np.tile`

Idea: Leverage on `np.tile` function to replicate `adj` over the number
of rows `D` has (i.e. `D.shape[0]`).

In [79]:
adj_stretch = np.tile(adj, (D.shape[0], 1))
adj_stretch

array([[9, 4, 4],
       [9, 4, 4],
       [9, 4, 4],
       [9, 4, 4]])

In [80]:
D * adj_stretch

array([[  2.7,  10. ,  14. ],
       [ 26.1, 110. ,   0. ],
       [  3.6,   5.2,  95.6],
       [129.6,  24. ,   9.2]])

Nice, it's shorter too, and slightly faster! **To appreciate even more** performance gain, of our `np.tile` solution, we could try increasing the size of D to a bigger structure:

In [81]:
D_large = np.random.rand(10**6, 10)
adj_large = np.random.rand(10)

In [82]:
D_large.shape, adj_large.shape

((1000000, 10), (10,))

In [83]:
%%timeit

# Create a new array filled with zeros, of the same shape as macros.
result_large = np.zeros_like(D_large)

# Now multiply each row of macros by cal_per_macro. In Numpy, `*` is
# element-wise multiplication between two arrays.
for i in range(D_large.shape[0]):
    result_large[i, :] = D_large[i, :] * adj_large

908 ms ± 7.32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [84]:
%%timeit 

adj_large_stretch = np.tile(adj_large, (D_large.shape[0], 1))

D_large * adj_large_stretch

53.5 ms ± 3.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


The loop-in-Python method takes `~1.5` seconds, the stretching method takes `~48` milliseconds, a `~75x` speedup.

And now, finally, comes the interesting part. 

You see, the operation we just did - stretching one array so that its shape matches that of another and then applying some element-wise operation between them - is actually pretty common. 

This often happens when we want to take a lower-dimensional array and use it to perform a computation along some axis of a higher-dimensional array. 

In fact, when taken to the extreme this is exactly what happens when we perform an operation between an array and a scalar - the scalar is stretched across the whole array so that the element-wise operation gets the same scalar value for each element it computes.

Numpy generalizes this concept into **broadcasting** - a set of rules that permit element-wise computations between arrays of different shapes, as long as some constraints apply. 

Incidentally, this lets Numpy achieve two separate goals - **usefulness as well as more consistent and general semantics**. 

Binary operators like `*` are element-wise, but what happens when we apply them between arrays of different shapes? Should it work or should it be rejected? If it works, how should it work? 

**Broadcasting defines the semantics of these operations**.

In [86]:
D.shape

(4, 3)

In [87]:
adj.shape

(3,)

In [97]:
D = np.linspace(1,10, 12).reshape(4,3)
D.shape

(4, 3)

In [99]:
adj = np.linspace(1,10,3).reshape(3)
adj.shape

(3,)

In [100]:
D * adj

array([[  1.        ,  10.        ,  26.36363636],
       [  3.45454545,  23.5       ,  50.90909091],
       [  5.90909091,  37.        ,  75.45454545],
       [  8.36363636,  50.5       , 100.        ]])

In [85]:
## Back to our example
D * adj  # Broadcasting

array([[  2.7,  10. ,  14. ],
       [ 26.1, 110. ,   0. ],
       [  3.6,   5.2,  95.6],
       [129.6,  24. ,   9.2]])

### How Broadcasting works

Element-wise operations on arrays are only valid when the arrays' shapes are either equal or **compatible**. 

The equal shapes case is trivial - this is the stretched array from the example above. What does **compatible** mean, though?

To determine if two shapes are compatible, Numpy compares their dimensions, starting with the trailing ones and working its way backwards. 

**For example**, for the shape `(4, 3, 2)` the trailing dimension is `2`, and working from `2` "backwards" produces: `2`, then `3`, then `4`.

If two dimensions are equal, or if one of them equals 1, the comparison continues. Otherwise, you'll see a ValueError raised (saying something like `"operands could not be broadcast together with shapes ..."`).

When one of the shapes runs out of dimensions (because it has less dimensions than the other shape), Numpy will use `1` in the comparison process until the other shape's dimensions run out as well.

Once Numpy determines that two shapes are compatible, the shape of the result is simply the **maximum of the two shapes' sizes** in each dimension.

**More here**: [Broadcasting Arrays in NumPy](https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/#id8)

## Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [102]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [103]:
v1 * 2

array([0, 2, 4, 6, 8])

In [ ]:
v1 + 2

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

In [ ]:
print('A * 2: ', '\n', A * 2)
print('A + 2: ', '\n', A + 2)

## Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [104]:
A * A # element-wise multiplication

array([[ 1,  4,  9],
       [16, 25, 36]])

In [105]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [106]:
A.shape, v1.shape

((2, 3), (5,))

In [107]:
A * v1  #Broadcasting

ValueError: operands could not be broadcast together with shapes (2,3) (5,) 